language: generic

matrix:
  include:
    - os: linux
      compiler: g++-8
      script: cd main/source/linux && make
      env: OPJ_CI_ARCH=i386
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - gcc-8-multilib
            - g++-8-multilib
            - libc6-i386
            - libcurl4-openssl-dev:i386
            - libpng12-dev:i386

    - os: osx
      compiler: clang
      before_script:
      - export CC=clang
      - export CPLUS=clang++
      script: cd main/source/linux && make
